site_name: Camila's Site Welcome

theme:
  name: material
  palette:
    scheme: default # light background / dark text
    primary: pink
    accent: white

  font:
    text: Open Sans
    code: Red Hat Mono

  logo: images/logo.png
  favicon: images/logo.ico

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/stylesheets.css
copyright: "© 2025 Camila — Designed with for everyone"
