site_name: Camila Simsiroglu

nav:
  - Home: index.md
  - Archive: archive.md
  - About: About-me.md
  - Documentation:
    - Blender Content:
      - Getting Started: Blender Content/Getting-Started.md
      - Modes in Blender: Blender Content/Modes-in-Blender copy.md
      - Modifiers: Blender Content/Modifiers.md
    - 3D Example: threejs-example.md


theme:
  name: material
  custom_dir: overrides
  
  palette:
    scheme: default
    primary: white
    accent: teal

  font:
    text: JetBrains Mono
    code: JetBrains Mono

  logo: images/logo.png
  favicon: images/logo.ico
  
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js
  - js/3d-viewer.js

plugins:
  - search

extra:
  generator: false

copyright: ""
